config/routes.rb
Rails.application.routes.draw do
  resources :my_threads, shallow: true do
    resources :comments
  end

end

app/models/my_thread.rb
class MyThread < ActiveRecord::Base
  validates :title, presence: { message: "入力してください"}
  validates :overview, presence: { message: "入力してください"}
  has_many :my_comments
end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  before_action :set_my_thread, only: [:show, :edit, :update, :destroy]

  # GET /my_threads
  # GET /my_threads.json
  def index
    @my_threads = MyThread.all
  end

<<<<<<< HEAD
  # GET /my_threads/1
  # GET /my_threads/1.json
  def show
    @comments = Comment.where(board_id: @my_thread.id)
  #  @comments = @my_thread.comments
    @comment = Comment.new
  end

  # GET /my_threads/new
  def new
    @my_thread = MyThread.new
  end

<<<<<<< HEAD
  # GET /my_threads/1/edit
  def edit
  end

  # POST /my_threads
  # POST /my_threads.json
  def create
    @my_thread = MyThread.new(my_thread_params)

    respond_to do |format|
      if @my_thread.save
        format.html { redirect_to @my_thread, notice: 'My thread was successfully created.' }
        format.json { render :show, status: :created, location: @my_thread }
      else
        format.html { render :new }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_threads/1
  # PATCH/PUT /my_threads/1.json
  def update
    respond_to do |format|
      if @my_thread.update(my_thread_params)
        format.html { redirect_to @my_thread, notice: 'My thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_thread }
      else
        format.html { render :edit }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_threads/1
  # DELETE /my_threads/1.json
  def destroy
    @my_thread.destroy
    respond_to do |format|
      format.html { redirect_to my_threads_url, notice: 'My thread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_thread_params
      params.require(:my_thread).permit(:name, :overview)
    end
end

app/helpers/my_threads/my_comments_helper.rb
module MyThreads::MyCommentsHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/my_threads/_form.html.erb
<% if current_user.id == @my_thread.user_id %>

  <%= form_for @my_thread do |f| %>
  <p>
    <%= f.label :title %><br>
    <%=f.text_field :title %>
  </p>
  <p>
    <%= f.label :overview %><br>
    <%=f.text_field :overview %>
  </p>
  <% if @my_thread.errors.any? %>
  <%= @my_thread.errors.messages[:title][0] %>
  <%= @my_thread.errors.messages[:overview][0] %>
  <% end %>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

<% else %>
  <p>編集できません</p>
<% end %>

app/views/my_threads/edit.html.erb
<h1>Editing My Thread</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_thread %> |
<%= link_to 'Back', my_threads_path %>
<% end %>

app/views/my_threads/index.html.erb
<h1>スレッド一覧</h1>
  <ul>
    <% @my_threads.each do |my_thread| %>
    <li>
      <%= link_to my_thread.title, my_thread_path(my_thread.id) %>
      <% if current_user.id == my_thread.user_id %>
      <%= link_to "編集", edit_my_thread_path(my_thread.id) %>
      <%= link_to "削除", my_thread_path(my_thread.id), method: :delete, data: {confirm: "Are you sure?"} %>
      <% end %>


</li>
    <% end %>
  </ul>
  <p><%= link_to "スレッド作成", new_my_thread_path %>

app/views/my_threads/new.html.erb
<h1>スレッド作成</h1>
<%= form_for @my_thread do |f| %>
<p>
  <%= f.label :title %><br>
  <%=f.text_field :title %>
</p>
<p>
  <%= f.label :overview %><br>
  <%=f.text_field :overview %>
</p>
<% if @my_thread.errors.any? %>
<%= @my_thread.errors.messages[:title][0] %>
<%= @my_thread.errors.messages[:overview][0] %>
<% end %>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/my_threads/show.html.erb
<h1><%= @my_thread.title %></h1>
<h2><%= @my_thread.overview %></h2>
<table>
  <% @my_comments.each do |my_comment| %>
    <tr>
      <td><%= my_comment.content %></td>
      <% if current_user.id == my_comment.user_id %>
      <td><%= link_to '編集', edit_my_comment_path(my_comment) %></td>
      <td><%= link_to '削除', my_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<%= render partial: "my_comments/form", locals: {my_thread: @my_thread, my_comment: @my_comment}%>
<br>
<% if current_user.id == @my_thread.user_id %>
<%= link_to 'Edit', edit_my_thread_path(@my_thread) %> |
<% end %>
<%= link_to 'Back', my_threads_path %>